GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbmd0aGFuaCIsImlkIjoiNjYyMWVlOWIyODYyZGEzMGNiNGM0M2NmIiwiaWF0IjoxNzEzNTA4MTM2fQ.wD4r2WsNwjy790Lhqj_GvtsIvuPkc7S3RZwZvcK2SV8

###
GET http://localhost:3003/api/blogs/661f8107c635a0d8f1c5a556

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbmd0aGFuaCIsImlkIjoiNjYyMWVlOWIyODYyZGEzMGNiNGM0M2NmIiwiaWF0IjoxNzEzNTA4MTM2fQ.wD4r2WsNwjy790Lhqj_GvtsIvuPkc7S3RZwZvcK2SV8

{
    "title": "fwefewfewfw",
    "author": "Truong Cong Thanh",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5
}

###
DELETE http://localhost:3003/api/blogs/66220f34fd4cd9254c8f84c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbmd0aGFuaCIsImlkIjoiNjYyMWVlOWIyODYyZGEzMGNiNGM0M2NmIiwiaWF0IjoxNzEzNTA4MTM2fQ.wD4r2WsNwjy790Lhqj_GvtsIvuPkc7S3RZwZvcK2SV8

###
PUT http://localhost:3003/api/blogs/5a422b3a1b54a676234d17f9
Content-Type: application/json

{
   "title":"React patterns",
   "author":"Michael Chen",
   "url":"https://reactpatterns.com/",
   "likes":7
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username":"coofkwofjwef",
   "name":"truong cong thanh",
   "password":"truongcongthanh"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
   "username":"congthanh",
   "password":"truongcongthanh"
}