DELETE http://localhost:3001/api/persons/6618c4a450ddc9b6fedc8298

###
POST http://localhost:3001/api/persons/ 
Content-Type: application/json

{
    "name":"CongThanh",
    "number":"127802434"
}

###
GET http://localhost:3001/api/persons/6618d0088c217aaf91ab74b3
